version: "2"
services:
  web_clasificados:
    image: web_clasificados
    container_name: web_clasificados
    build: .
    ports:
      - 5000:80
    volumes:
      - /home/ro/Databases/web_clasificados/logs:/app/logs
    restart: unless-stopped
  postgres_clasificados:
    image: postgres
    container_name: postgres_clasificados
    environment:
      - TZ=America/Mexico_City
    volumes:
      - /home/ro/Databases/postgres_clasificados:/var/lib/postgresql/data
    ports:
      - 5433:5432
    restart: unless-stopped
