version: "2"
services:
  web_clasificados:
    image: web_clasificados
    container_name: web_clasificados
    build: .
    ports:
      - 5000:80
    volumes:
      - /home/ro/Databases/web_clasificados/logs:/app/logs
    restart: unless-stopped
  
networks:
  default:
    external:
      name: postgres_default